### ISSUE TITLE
New VCEP Variant Tracker for NF VCEP

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#104]
- [x] Danielle needs to add NF VCEP to ClinVar Report BQ Support Tables
- [x] Once report autogeneration process in place, use NF VCEP as a test to generate a new report

**Comment by RyanFWebb** [comment]
Here is the new report: [NF VCEP Variation Tracker](https://docs.google.com/spreadsheets/d/1Snhvpg3MbHzQRq4FvHTSVvCk3k_4lcxi005KR5myMSU/edit?gid=0#gid=0)
