### ISSUE TITLE
Confirm Out of Date Alerts are working correctly

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#105]
Question from Jessica Hatton about the DICER1 VCEP Variant Tracker and how out of date variants are calculated, see examples below https://docs.google.com/spreadsheets/d/125xxFPtlFeBaYpRDWb4odgGIR7_cBHmpsB33cVnc4Yg/edit?usp=sharing

<p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt;">Thanks for clarifying.  So, if calculating based on “Date Last Evaluated,” it looks like DICER1 has the following out-of-date variants:<u></u><u></u></span></p><p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt;"><u></u> <u></u></span></p>
Name | Germline classification | Germline date last evaluated
-- | -- | --
NM_177438.3(DICER1):c.4748T>G (p.Leu1583Arg) | Likely pathogenic | 17-May-22
NM_177438.3(DICER1):c.5563C>T (p.Arg1855Ter) | Uncertain significance | 18-May-22
NM_177438.3(DICER1):c.5465A>T (p.Asp1822Val) | Likely pathogenic | 18-May-22
NM_177438.3(DICER1):c.5138A>T (p.Asp1713Val) | Likely pathogenic | 18-May-22
NM_177438.3(DICER1):c.5107C>T (p.Arg1703Cys) | Uncertain significance | 18-May-22
NM_177438.3(DICER1):c.5096-12G>A | Likely pathogenic | 18-May-22
NM_177438.3(DICER1):c.4024C>T (p.Arg1342Cys) | Uncertain significance | 18-May-22
NM_177438.3(DICER1):c.2642T>C (p.Leu881Pro) | Likely pathogenic | 18-May-22
NM_177438.3(DICER1):c.1719AGA[1] (p.Glu574del) | Uncertain significance | 18-May-22
NM_177438.3(DICER1):c.238G>T (p.Glu80Ter) | Likely pathogenic | 18-May-22
NM_177438.3(DICER1):c.2T>C (p.Met1Thr) | Uncertain significance | 18-May-22

<p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt;"><u></u> <u></u></span></p><p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt;">However, the DICER1 variant tracker shows “0” out of date variants. . .  Perhaps I’m refreshing it incorrectly?  (Screenshot below)</span></p>

**Comment by RyanFWebb** [comment]
It looks like the automatic refresh that pulls in data in the BigQuery connected sheet had been turned off. It's back on now and everything looks like it should be up to date. The alerts tab and home sheet's pivot table are now showing out of date variants.

Ready to close pending your/Jessica's review.
