### ISSUE TITLE
New VCEP Variant Trackers

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#109]
Hi Ryan,

Can you please generate reports for the following VCEPs? Both are in the ClinVar Report BQ Support Table Sheet

[ClinGen Hereditary Hemorrhagic Telangiectasia Variant Curation Expert Panel; ClinGen](https://www.ncbi.nlm.nih.gov/clinvar/submitters/509488/)

von Willebrand Disease VCEP

If this is something I can now do with the report generator just let me know.

Thanks!

**Comment by RyanFWebb** [comment]
Danielle and I walked through automatically generating new reports together.
