### ISSUE TITLE
Document onboarding process so VCEPs can use VCEP Variation Trackers

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#13]
Larry and Danielle to document the steps so users can interact and refresh the sheets

- [ ] Keep sheet in accessible Google drive https://drive.google.com/drive/folders/10vEGdTMJ5IxajPVwMV2jfRMFJadlXLM4?usp=share_link
- [ ] Add user to Google permissions list https://console.cloud.google.com/apis/credentials/consent?project=clingen-dx
- [ ] Let user know they need to accept permissions to refresh

**Comment by dazzariti** [comment]
@larrybabb I am happy to help on this - not sure where this documentation should live?

**Comment by larrybabb** [comment]
@dazzariti i'm going to archive this ticket until you and I decide to do something more formal. If you disagree, please "unarchive it"

**Comment by dazzariti** [comment]
@larrybabb I'm going to move this one out of the Archive and revisit the process.

**Comment by dazzariti** [comment]
@larrybabb My understanding is everyone who needs access to refresh ClinVar data in the VCEP Variant Trackers should be added to the clingen-data-read Google Groups https://groups.google.com/a/broadinstitute.org/g/clingen-data-read

I have added anyone to it that has requested access to the VCEP Variant Trackers, I have removed them from the Google OAuth list

I have shared this sheet with Larry and will keep up to data everyone I add to the Google Group and indicate that they are joining for the purpose of refreshing the VCEP Variant Trackers
https://docs.google.com/spreadsheets/d/1lGEb2W9-5xDPzyQ8WHgO9YdAoJIyjmYtNNzmIxCMGUU/edit?usp=sharing
