### ISSUE TITLE
Capture QC ok/fixed flags on Breakout tabs and show on main QC report

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ingest-reports#35]
Heidi would like to be able to have an indicator on the main QC report from the [CvCuration QC & Statistics v2](https://docs.google.com/spreadsheets/d/1DmYRW7YYmLnsYuQNkHEMAOx-d6mdLD5lCTky0p1UDbw/edit#gid=609885799&fvid=67087161) google sheet that allows them to see which entries have been QC'd.  This will allow them to prioritize which general curations need attention without trying to resolve previously QC'd records manually.

**Comment by hdziadzio** [comment]
@larrybabb please verify if you've completed this.

**Comment by dazzariti** [comment]
Discussed with Heidi, this is now an out of date request - @larrybabb are you ok closing this one and starting over?

**Comment by larrybabb** [comment]
I think we should discuss the design task and solution needed to manage the curations being submitted and how we will be able to go back and view them as we move forward. We can create a new ticket for that and then close this or leave this open until we have a better collective sense of what we will need.

**Comment by dazzariti** [comment]
I have added this to the CvC check in agenda

**Comment by dazzariti** [comment]
I am closing this as it's related to the v2 sheet and we currently use v3. If still needed, we can create a new ticket.
