### ISSUE TITLE
Add "Tracking" tab to "VCEP Variation Tracker"

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#4]
As discussed on Nov 15 weekly meeting, add a Tracking tab to the VCEP Variation Tracker reports - mocked up here https://docs.google.com/spreadsheets/d/1D0SY3og-0h8ATbxJV7itJNg7MWR8xRTZBLvFfc7cqzo/edit?usp=sharing on the "Tracking Tab"

The ability to copy and paste a variant from the Alerts or Priorities tab into a format that paste right in to the Tracking tab would be very helpful OR the ability to select a variant row on the Alert or Priority tab and indicate you'd like to add it to the Tracking tab, and the relevant information will automatically be added to bottom row of the Tracking tab.

Fields to add to "Tracking" tab include:

- Variant ID	
- Variant Name	
- Reason	
- Date Added to Tracking Sheet	
- VCEP Notes	
- Reviewed by VCEP? Y/N	
- Resubmit to ClinVar? Y/N

Add the following columns to the "Alerts" and "Priorities" tab that would correspond to the Tracking tab

- Variant Added to Tracking Tab Y/N
- Show "VCEP Notes" field from Tracking tab

Definition of Done: Tracking tab added to all active EP reports, with ability to select variants from Alert and Priorities tab and automatically add to Tracking tab.

**Comment by larrybabb** [comment]
@dazzariti I think we need to have a quick sync up on walking through exactly what we want to do with the Tracker and therefore how it will work with both the Alert and Priority records once it is established. I'm sure you can help me keep it simple for the first release.

**Comment by dazzariti** [comment]
I can see if we can grab some time with Marina and the curators on Thursday? Happy to meet earlier than that, Tuesday and Wednesday wide open.

**Comment by dazzariti** [comment]
Updated list of fields for Tracking tab (discussed during Feb 26 Broad team feedback session):

- Variant ID
- Variant Name
- VCV ID
- VCEP SCV (If available)
- Alert/Priority Type
- Start Tracking
- End Tracking
- Status (Note: Marina is defining multiple choice options)
- VCEP Notes
- VCEP Reviewed?
- ClinVar Resubmit? Y/N
- Assigned To
- Resolution (Note: Marina is defining multiple choice options)

Additional Tracking Tab features discussed:

-“Add to Tracking” tab feature on a particular row of the Priorities or Alerts tab - if the same variant and alert type is already added - user will get a message and will need to choose to add a duplicate or override previous - if  the same variant but a different alert/version user is notified
-Ability to "Close Out" a tracked variant
-Add a “Action” on the Tracking tab “Hide from Alerts/Priorities tab”

**Comment by dazzariti** [comment]
Update from Feb 14th discussion - the Tracking tab should not block the production of reports for approved VCEPs with Alert/Priority tab

**Comment by dazzariti** [comment]
Discussed on June 13 weekly meeting, expected MVP July 31st

Highest VCEP Variant Tracker priority at this time

**Comment by larrybabb** [comment]
Reassigning this to @RyanFWebb since he's been completing this work the past month.

**Comment by dazzariti** [comment]
Based on our discussion last week that anyone who wants to use the Tracker tab needs to be on the Authorized list - I am going to send out an email looking for VCEPs to pilot the Tracking tab. @RyanFWebb I would save yourself some time and not update any more sheets with the Tracking tab until we know who wants to use it - and then we'll focus on those. 

Let's discuss this week, we can probably close this ticket and make new ones moving forward as new requests come in.

**Comment by dazzariti** [comment]
Closing this ticket and adding a new one with the requests to add Tracking tabs for additional VCEPs
