### ISSUE TITLE
Tracking tab tasks

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest-reports#44]
Dependent on Tracking Tab
- [x] Add column and filter “Is this variant in Tracking tab?” Yes/No 
- [x] Consider if the Status of the tracking should also be indicated on the relevant Alerts/Priorities row

**Comment by RyanFWebb** [comment]
This is fine with me. The feature to indicate how many records exist for each variant with the newest at the top was not included in this version. If we still want that feature, we may want to keep the ticket or make a new one @dazzariti.

**Comment by dazzariti** [comment]
Thanks Ryan! I will start a new ticket with feedback we collect from the pilot and will add the " Indicate how many records there are for each variant with the newest at the top" to it
