### ISSUE TITLE
Update "VCEP Impact Report Nov 30 2023"

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#54]
As discussed on 9/5  Broad ClinGen Weekly meeting

Update the "VCEP Curated Variants Calculations April 2022"

Ask: The goal is to compare the overall classification in ClinVar PRIOR to a ClinGen VCEP submission, compared to the overall status with today’s current VCEP classification 

https://docs.google.com/spreadsheets/d/1narS_N7kmkTl8OM1B7JRZqpZtTzf4QPjCthKIMz6hsw/edit?usp=sharing

**Comment by dazzariti** [comment]
Clarified the plan with Heidi:

Update the data in this sheet https://docs.google.com/spreadsheets/d/1narS_N7kmkTl8OM1B7JRZqpZtTzf4QPjCthKIMz6hsw/edit?usp=sharing on the "VCEP variant summary release change history tab"  (this would be a task for Larry and Ryan, I'm joining their meeting tomorrow and can discuss)

Once updated data is available, someone on the Broad/ClinGen team update the data Kelsea put together https://docs.google.com/spreadsheets/d/1u1Bitj4ClcbOGbSa5pM_VeN8ikZiQfbOwpVfqUXonUw/edit?usp=sharing - specifically the "Classification Changes After EP Assertion" pie chart - the goal is to compare the overall classification in ClinVar PRIOR to ClinGen VCEP submission, compared the overall status with today’s current VCEP classification

Based on the results of that exercise, we'll determine if it's still necessary to identify all the pilot variants and remove them from the analysis

**Comment by dazzariti** [comment]
@dazzariti will add an example of what this query would look like

**Comment by larrybabb** [comment]
@dazzariti I created a new script that I hope we can just use going forward. Here's the first draft
https://docs.google.com/spreadsheets/d/1gsl19l95JdCSD2HWSmoovkKhGRRo3nDWOUlaH5i3hEI/edit#gid=1654405943
It's just a result set of the 5K+ SCVs that VCEPs have in clinvar as of 11/26/2023.  I created a read.me page to explain the data in the report. I think that this should give us a lot to use for generating graphs and reports. But like everything we should probably show it to Heidi and the group and get feedback. If there's no major change to this then I can make this updateable by the users, right now it's static.
Let me know what you think.

**Comment by dazzariti** [comment]
@larrybabb Before doing too much with this report to make it undateable, could you generate again with the latest ClinVar data release? https://docs.google.com/spreadsheets/d/1gsl19l95JdCSD2HWSmoovkKhGRRo3nDWOUlaH5i3hEI/edit#gid=1654405943
