### ISSUE TITLE
Adding Tracking tab to VCEP reports for pilot

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#55]
Hi Ryan, these are the groups that I've discussed the Tracking tab with and would like to prioritize you adding the tab to their reports. I will be working with making sure the VCEP personnel have the appropriate Google permissions. 

- [x] Platelet
- [x] PAH

**Comment by RyanFWebb** [comment]
Platelet's variant tracker is good to go.

**Comment by dazzariti** [comment]
Thank you!
