### ISSUE TITLE
Create VCEP Trackers for newly approved VCEPs

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#57]
Here are the next sets of VCEPs I'd prioritize for creating reports for, these groups are now approved and have either submitted to ClinVar or should be shortly https://docs.google.com/spreadsheets/d/1bADskBcobHTmmXungY09beWPDEa1nqM-PP__86yGVj0/edit?usp=share_link

Thrombosis VCEP (ClinVar Organization ID: 509282, added to ClinVar Report BQ Support Tables)
ENIGMA BRCA1 and BRCA2 VCEP (Organization ID:  509268, added to BQ table)
Coagulation Factor Deficiency VCEP (haven't submitted to ClinVar yet)
Severe Combined Immunodeficiency Disease VCEP (Org ID 509310, added to BQ table)

**Comment by RyanFWebb** [comment]
The following sheets have been created:
[Thrombosis VCEP Variation Tracker] (https://docs.google.com/spreadsheets/d/1LN6T6a9Mw0tKglccIJrbZF0IVuhTqOPuwG0asbjGHrQ/edit#gid=465571331)
[ENIGMA BRCA1 and BRCA2 VCEP Variation Tracker] (https://docs.google.com/spreadsheets/d/1an5UnFA6Gsjt8w0Y0yCds95ur-nPWpbUDtxEFipuxgs/edit#gid=465571331)
[Severe Combined Immunodeficiency Disease VCEP Variation Tracker](https://docs.google.com/spreadsheets/d/15GCwqsKh7zVrGGyKvVO2PvbQimDdbqY3qItG7RHGyZY/edit#gid=0)

The Coagulation Factor Deficiency VCEP Variation Tracker should be ready later today.

**Comment by RyanFWebb** [comment]
The Coagulation Factor Deficiency VCEP Variation Tracker is ready as well:
[Coagulation Factor Deficiency VCEP Variation Tracker](https://docs.google.com/spreadsheets/d/13nhQfje6nvksqQvxREmFPk_b_frq6odYFz3tfFWMX3g/edit#gid=0)
