### ISSUE TITLE
Add Tracking tab to VCEP reports

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#59]
Please add the Tracking tab to the follow VCEP reports

- FH https://docs.google.com/spreadsheets/d/1GUjW2Gq1Wd5jyNjISGlRJg36GGXuT0XJfqnu_44eLzY/edit?usp=sharing
- HBOP https://docs.google.com/spreadsheets/d/1rpblfPar2xtRZUMOYoTAhVWn2U4SnRQ1g9SlC836mt0/edit?usp=sharing

**Comment by RyanFWebb** [comment]
There is an issue populating the FH submitted_submitter_abbrev in the alerts tab. I believe this is causing an issue with the tracker tab which I need to trouble shoot.

**Comment by RyanFWebb** [comment]
Both the FH and HBOP tracker sheets should be good to go!

**Comment by RyanFWebb** [comment]
There is still an issue with FH submitted_submitter_abbrev, but the sheet is functional otherwise.
