### ISSUE TITLE
GenomeConnect Variation Tracker: Requested enhancements

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#61]
Background: Once the Genome Connect Variation Trackers are available with the existing Excel-based functionality, the GenomeConnect team would like to request the following enhancements.

Note: Once (https://github.com/clingen-data-model/clinvar-ingest-reports/issues/62) is complete, @dazzariti will rereview these enhancement requests with Jules to see if anything has changed or been reprioritized

1. The report to be formatted as one sheet with all 8 registries, with a feature to select information pertaining to each individual registry

GenomeConnect; Clinical Genome Resource
GenomeConnect - Invitae Patient Insights Network
GenomeConnect - Brain Gene Registry
GenomeConnect-Association for Creatine Deficiencies; Association for Creatine Deficiencies
GenomeConnect - CFC International
GenomeConnect - CureCADASIL
GenomeConnect - GM1
GenomeConnect - No Stomach For Cancer

2. Inheritance from submissions pulled into the report (Allele Origin)
3. Add a column on Alert tab, "Date of first ClinVar data release when variant was flagged" - The intention of this request is to track how long the variant has been on GenomeConnect's radar
4. Add a column on Alert tab for "Local ID" - this value is included in XML, adding this value makes it very helpful for the GenomeConnect team to map back to the participant with that variant
5. In addition to flagging new additions for the Variant classification from the GenomeConnect testing lab against previous classification submissions from the same lab report, would it be possible to add the date added?
6. For Variant classification from the GenomeConnect testing lab against EP classifications - could we also flag new additions and include the date added, if possible?

Questions:
Should we add additional submitters in the future, what will the process look like to have them added to the report? We expect to partner with additional registries, so could this be considered?

**Definition of Done**: All enhancements described above are available in the Google-sheet based Variation Tracker for the following GenomeConnect ClinVar submitters:

GenomeConnect; Clinical Genome Resource
GenomeConnect - Invitae Patient Insights Network
GenomeConnect - Brain Gene Registry
GenomeConnect-Association for Creatine Deficiencies; Association for Creatine Deficiencies
GenomeConnect - CFC International
GenomeConnect - CureCADASIL
GenomeConnect - GM1
GenomeConnect - No Stomach For Cancer

**Comment by larrybabb** [comment]
This should all be merged into the original 'blocking' issue that is now an epic broken down into smaller tasks.  I am going to move the content in the description over to the #62 Epic and reference this original issue. I will move this to the Archive state afterwards.

**Comment by larrybabb** [comment]
Much of this has been done during the Epic issue #62 which was originally blocking this.  At this point, it makes sense to merge the description from this issue with that epic and create sub-issues to address any remaining items. Then we can archive this issue.

**Comment by dazzariti** [comment]
@larrybabb I think much of this was discussed in your back and forth with Caitlin and Jules when finalizing the new reprt. I think it makes sense to close this ticket now and make new tickets as they're requests come in, based on using the new Google-based report.
