### ISSUE TITLE
GenomeConnect Variation Tracker: Transition Excel-based functionality to Google-based Variation Tracker

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/clinvar-ingest-reports#62]
**Goal**: Replace Excel-based reports with Google-sheet based reports fed by ClinVar ingest data for the following ClinVar GenomeConnect submitters:

- GenomeConnect; Clinical Genome Resource
- GenomeConnect - Invitae Patient Insights Network
- GenomeConnect - Brain Gene Registry
- GenomeConnect-Association for Creatine Deficiencies; Association for Creatine Deficiencies
- GenomeConnect - CFC International
- GenomeConnect - CureCADASIL
- GenomeConnect - GM1
- GenomeConnect - No Stomach For Cancer

SP Ticket Link: https://broadinstitute.atlassian.net/jira/software/projects/CGSP/boards/872?issueParent=468029&selectedIssue=CGSP-424

**INFORMATION TO BE INCLUDED ON REPORT: (Collected by Kelsea and Larry, in discussion with Jules Savatt)** 
**1. Variant classification from the GenomeConnect testing lab against previous classification submissions from the same lab** (Invitae example: https://www.ncbi.nlm.nih.gov/clinvar/variation/1063220/?new_evidence=true) **HIGH PRIORITY**
- Display all variants from the testing lab. Within this list, flag all variants that are conflicting with this instance of GenomeConnect testing lab classification. Also note if they agree. [This equates to the **LabConflicts** and **Lab Consensus** tabs on the old report - can be combined here] _Within this list of all variants, flag which ones are new additions_
- Flag if no GTR OrgID is identified for the testing lab (the id is in the xml when available) [This equates to the **LabNoOrgID** tab on the old report]
- Flag if the testing lab has an OrgID but has no other SCVs on the variant in ClinVar [This equates to the **LabNotSubmitted** tab on the old report]

**2. GC submissions against all other submissions** **NICE TO HAVE**
- Display all ClinVar variants where the only submission is from GenomeConnect [This equates to the **AllNovel** tab on the old report]
- Display all ClinVar variants where there is a GenomeConnect submission [This equates to the **AllSub** tab on the old report] _Include GCEP classification(s) here_

**3. Variant classification from the GenomeConnect testing lab against EP classifications** **HIGH PRIORITY**
- Flag any variants in which the GenomeConnect testing lab classification conflicts with EP classification [This equates to the **EPConflict** tab on the old report]

Example of November 2021 [GenomeConnect report](https://docs.google.com/spreadsheets/d/1t1AmKLXwIbsIOJbCCMkPDDuXFbtCOu5a/edit#gid=1355336813) pulled from code Tam wrote. 

> NOTE: (added 2/13/2024) combining the requrest for issue #61 to this epic since some of the items on that request got addressed during the early stages of this epic. All remaining items still need to be reviewed and converted into sub-issues here.  To see the original #61 request go [here](https://app.zenhub.com/workspaces/genegraphdxclinvar-60340fb9898dae001107e94e/issues/gh/clingen-data-model/clinvar-ingest-reports/61).

**Definition of Done:** GenomeConnect team no longer needs to be sent Excel-based reports, can access all data that was available in Excel-based report through a Google sheet-based Variation Tracker with the ability to refresh the data to reflect a new ClinVar data release for the following submitters:

- GenomeConnect; Clinical Genome Resource
- GenomeConnect - Invitae Patient Insights Network
- GenomeConnect - Brain Gene Registry
- GenomeConnect-Association for Creatine Deficiencies; Association for Creatine Deficiencies
- GenomeConnect - CFC International
- GenomeConnect - CureCADASIL
- GenomeConnect - GM1
- GenomeConnect - No Stomach For Cancer

**Comment by larrybabb** [comment]
adding description info from #61 to this epic so that we have one place to go through and audit all the requests made over the past couple of years and assure nothing was missed.

**Comment by dazzariti** [comment]
@larrybabb I removed the VUS report request https://github.com/clingen-data-model/clinvar-ingest-reports/issues/90 from this Epic - otherwise all the tickets related to transitioning away from Excel based reports is complete. The VUS report is separate issue so I think it makes sense to move it and close this Epic. Congrats!
