### ISSUE TITLE
ClinVar variation tracking reports (EPs, GC, Labs,...)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ingest-reports#63]
**Goal**: Redevelop ClinVar Discrepancy Reports using the new ClinVar data stream to represent ClinVar data on the ClinGen website. Three different reports/queries will be needed based on each target audience: 
- VCEPs (_first in development_)
- GenomeConnect (_second in development_)
- Labs/Submitters (_third in development_)

**Important question:** How long are these reports going to be utilized in this fashion? When/if there are plans to transfer this over to the VPT and given this, how much effort should go into this project? (ie Minimal effort if this will only be utilized for a short amount of time)

Link to Zoom call with Larry, Steven, Jules, and Kelsea on 01/11/22 : [google drive link](https://drive.google.com/file/d/11A_GXnhEP8kZaexSsPercmxeBy2YckIi/view?usp=sharing) - Logistics of pilot report(s)
- [Meeting notes/agenda](https://docs.google.com/document/d/1z5JFRh8pFHm-2Uew2ZwGxxjK8dSd4bMUDTWNspRrTNI/edit)

**DoD:** All three types of reports are in production

[Epic on CGSP Board](https://broadinstitute.atlassian.net/jira/software/projects/CGSP/boards/872/roadmap?selectedIssue=CGSP-423)

**Comment by dazzariti** [comment]
I think this can be considered closed - we have multiple other tickets representing these requests
