### ISSUE TITLE
Add Tracking Tab to the following VCEP Reports

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#65]
Please add Tracking tabs to the following reports based on coordinator requests:

Mitochondrial https://docs.google.com/spreadsheets/d/1uOQ99Rt44scfmvOZQg-4i54FnO8yxB6iqhedg0NHyoc/edit?usp=sharing

CCDS - https://docs.google.com/spreadsheets/d/1rw7SGLUkceuDEqOEDyCBjZXxzUwqfHOSKxn07JAzBVg/edit?usp=sharing

Lysosomal - https://docs.google.com/spreadsheets/d/14sdMMsPZ_WnPuqbItosAZyqjoxHusjoRRRC7lXPEjuo/edit?usp=sharing

**Comment by RyanFWebb** [comment]
The Mitochondrial VCEP is good to go.

**Comment by RyanFWebb** [comment]
The CCDS VCEP is good to go.

**Comment by RyanFWebb** [comment]
The Lysosomal VCEP is good to go.
