### ISSUE TITLE
New VCEP Variant Tracker Reports

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#71]
Hello, could you please generate a VCEP Variant Tracker report for the Leber Congenital Amaurosis/early onset Retinal Dystrophy Variant Curation Expert Panel? They haven't submit to ClinVar yet but are recently approved and interested in using the report. Thanks!

Also adding on the Pulmonary Hypertension VCEP who is about to be Step 4 approved.

**Comment by RyanFWebb** [comment]
Both VCEP Tracker reports are good to go.
[LCAeoRD VCEP Tracker](https://docs.google.com/spreadsheets/d/1lAgPwTKU5CQBMJi_XWyrlv0xbxcqvSs0ge9RbXL2UBg/edit#gid=0)
[Pulmonary Hypertension VCEP Tracker](https://docs.google.com/spreadsheets/d/1GHOBvt7_pjy2SAqbtWnx3Y0msacaN5YavBGteLwibqk/edit#gid=173192021)

**Comment by dazzariti** [comment]
Thank you! These have been shared with the VCEPs.
