### ISSUE TITLE
Create VCEP Variant Tracker for VCEPs about to be approved

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#73]
Hi Ryan, we have two VCEPs that should be approved soon and I'd like to get them set up with their VCEP Variant Tracker reports (even though they aren't submitting to ClinVar yet and don't have a submitter ID) when you have a chance, thanks!

- VHL 
- Epilepsy Sodium Channel

**Comment by RyanFWebb** [comment]
Both sheets are ready for review:
[VHL](https://docs.google.com/spreadsheets/d/1lshaHvkco260V85ot22__ke2itwTKDJbvMMDkOUgmYs/edit#gid=0)
[Epilepsy Sodium Channel](https://docs.google.com/spreadsheets/d/1XxmgmRK25Kk9WmjxK1Ra8j2X0542G8Pb8hrvECqvqVU/edit#gid=347243010)

**Comment by RyanFWebb** [comment]
Updated versions with authorization and API fixes:
[VHL](https://docs.google.com/spreadsheets/d/1hldoR4JRotShgOV0uvsBbekKqQ4WNptwy8B1X4M9U4Y/edit#gid=0)
[Epilepsy Sodium Channel](https://docs.google.com/spreadsheets/d/14zFP4a7pEJY_wpLG9YXMVjGxoZ_S0vrpapuCeIM7rTE/edit#gid=0)

**Comment by dazzariti** [comment]
Looks great, thanks!
