### ISSUE TITLE
Design appoach to resetting baseline filterviews on a tab

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ingest-reports#79]
DoD
Demonstrable google sheet with  a couple predefined filterviews that can be reset by the user (via button or menu or running an app script) such that if the user deletes, modifies or adds filterviews to said tab that it will bring back/reset just the predefined filter views.  These predefined filter views can exist in the app script as json if that is easy to do.

_Extra credit.  put the predefined elements of the fitler views in a separate tab such that it can be modified by the user and used to reset/re-add these filter views on the original tab_

Reset/Fix Alert Filter Views. 
Allow maintainers to sync Alert Filter Views from Master configuration on any existing VCEP Tracker google sheet.
Create a sandbox google sheet with a simple table and 2 simple filter views (x 1 and x 2) on that table in a tab called "x"
Put a button on this "x" (top row) that is assigned to a script that will execute the "x" app script
In the "x" script read and display the filter views on the "x" tab in an app script console.

**Comment by RyanFWebb** [comment]
Hard code in 2 filter views for mock Alert tab in the sandbox. We will change the settings of the filter views and the updateFilterViews function should reset the the filter views to defaults in addition to updating their ranges. Recreate missing filter views from static map definitions, don't touch custom filter views from VCEP (except for adjusting its range). Look into deleting them and re-adding them.

Eventually put asterisk in front of our default filter views to note that we manage those filters and will maintain them, with them being reset from time to time.

**Comment by RyanFWebb** [comment]
Met with Larry on March 1. We have a functional solution and are now working on creating BQ tables to automatically read filterViews while learning to build the rest of the VCEP Tracker Report in this manner.

**Comment by RyanFWebb** [comment]
@larrybabb Review issue to confirm that the solution discussed on March 1 is functional.
