### ISSUE TITLE
Add tracking functions to GC submitter reports

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ingest-reports#83]

**Comment by larrybabb** [comment]
During a planned meeting the week of Feb 22, priorities will be discussed on whether and what tracking functions will be necessary to deploy the new GC submitter google sheets. After that meeting more details will be provided and determination on when the work will be completed will be discussed and determined.

**Comment by larrybabb** [comment]
@dazzariti I reviewed this new GC tracker sheet https://docs.google.com/spreadsheets/d/1dPgtlL9FVYCYrU9aWe0JQgeM_bpHcoM9QqgeQGCtixM/edit?gid=0#gid=0 with Caitlin on 6/19 at 4p ET. It has the ability to be refreshed and also has the basic tracking functions. 

You should also try to open it and refresh it to make sure you know what and where it is.  I put this in the same folder with the Variant Tracking Reports folder (in the ClinGen Site shared google drive).  I added caitlin's gmail address to clingen-data-read google group and she was able to access the report and refresh it after accepting the permissions.

She is going to share with Jules, but (again) I think you need to be in the loop on this in case you need to twiddle permissions or locations or whatever.

Once you know where this is and don't have any issues or questions you can close this ticket.

**Comment by dazzariti** [comment]
I followed the steps for the VCEP Tracker Permissions and have asked both Jules and Caitlin to test refreshing the data
