### ISSUE TITLE
External users can't refresh vcep or other clinvar-based google sheets

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ingest-reports#88]
Any non-broadinstitute.org based user seems to recently been presented with an exception when they try to "Refresh" a VCEP google sheet (e.g. ACADVL and FH users).

My initial analysis proves that this is occurring on any external google account not affiliated with broadinstitute.

**Comment by larrybabb** [comment]
A month ago or less I did some major updates to how the data is being retrieved which introduced a  new resource that requires additional access (the ClinVar Report BQ Support Tables google sheet in the B/G shared google drive).  This introduced the breaking change since the "Refresh" function now needs the ability for the user to read that sheet.  So, to try to make things simpler all around, I think we should simply add any google account users that need to work with any of our clinvar-based google sheets to the clingen-data-read@broadinstitute.org google group.  I've assigned this google group to the ClinVar Report BQ Support Tables google sheet in the B/G shared google drive with View permissions and we should make sure this google group has editor permissions on the VCEP Report shared drive in the ClinGen Site shared google drive (versus individually adding accounts to that folder).  And we can stop adding folks that do not need the chrome extension access to the Oauth Consent list of test users.

**Comment by larrybabb** [comment]
@dazzariti if you and/or @hdziadzio could work to create a list of google accounts for all vcep and other google sheet users and add them to the clingen-data-read@broadinstitute.org google group. Additionally, one of you will also need to make sure this google group email is added as an Editor to the [VCEP Variant Tracking Reports folder](https://drive.google.com/drive/folders/10vEGdTMJ5IxajPVwMV2jfRMFJadlXLM4) in the ClinGen Site shared google drive (once that is done the individual entries that are in that shared drive can be removed).  This google group is also currently added as a Viewer on the [ClinVar Report BQ Support Tables](https://docs.google.com/spreadsheets/d/1bADskBcobHTmmXungY09beWPDEa1nqM-PP__86yGVj0/edit#gid=2067576827) which will fix the breaking change that caused this bug to happen.  You should also be able to remove all google account users from the GCP Oauth Consent test users list that do not need access to the chrome extension. I mistakenly instructed us to do this for all users that needed access to the clinvar ingest data (which is now really based on this google group membership).  NOTE: all chrome extension users still need to be in the Oauth Consent list (which might possibly be managed by adding a *new* google group to the test list so that we don't have to manage membership through the GCP Oauth screen - but we will need to test this if it is desirable).

**Comment by dazzariti** [comment]
Thanks Larry, just an update - 

- I've added clingen-data-read@broadinstitute.org as a contribute (can add and edit files) on the [VCEP Variant Tracking Reports folder](https://drive.google.com/drive/folders/10vEGdTMJ5IxajPVwMV2jfRMFJadlXLM4)
- I now add all VCEP Variant Tracker users who want to refresh/track the data to the ClinGen Data reads Google Group, I started a list here to indicate which members are on the list for the VCEP Reports (I've set them all to no mail) https://docs.google.com/spreadsheets/d/1lGEb2W9-5xDPzyQ8WHgO9YdAoJIyjmYtNNzmIxCMGUU/edit?usp=sharing
- I have removed all the VCEP Variant Trackers users from the GCP Oauth list
