### ISSUE TITLE
Using BQ support table to update filter views

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/clinvar-ingest-reports#96]

**Comment by RyanFWebb** [comment]
Generate necessary data in individual tracker sheets suited to update filter views automatically from the BQ Support Tables.

**Comment by RyanFWebb** [comment]
Done, now using imported data to update filter views.

**Comment by RyanFWebb** [comment]
Reviewed with Larry on 4/12/24. Ready to implement across sheets with minor refactoring. All set for Review/QA.
